### ISSUE TITLE
Servers does not work

### ISSUE THREAD

**Issue by frenchfish** [gnh1201/potplayer-lingva#4]
Hello look like servers does not work anymore lingva ml  and catswords

**Comment by gnh1201** [comment]
Hi. Thanks for your report. I will investigate this issue.

**Comment by gnh1201** [comment]
I'm pleased to share some good news.

We have restored our Lingva instance at `translate.catswords.net`. Since access to lingva.ml is currently unstable, please feel free to use our instance instead.

Additionally, our Lingva instance is hosted on major cloud infrastructure. If you'd like to support stable operation, consider [becoming a sponsor (starting at just $1 per month)](https://github.com/sponsors/gnh1201).

Thank you!

**Comment by frenchfish** [comment]
Hello/I tried it/ I passed test but it still doesnt dshow subtitles in
potplayer[image: 2024-11-23_23-12-19.png][image:
2024-11-23_23-22-05.png][image:
2024-11-23_23-23-01.png]

вс, 10 нояб. 2024 г. в 14:57, Namhyeon, Go ***@***.***>:

**Comment by gnh1201** [comment]
Please check this instructions:

1. ***Set an available lingva server:*** Open the context menu with right mouse click, and go to Preferences -> Extensions -> Subtitle Translation -> Choose `Lingva(Google) translate` -> Click `Login...` button -> Input the server URL `https://translate.catswords.net`

![Set an available lingva server](https://github.com/user-attachments/assets/54d4307a-755f-43c5-aa8c-dc69928600c6)

2. ***Set to always use subtitle translation***: Open the context menu with right mouse click, and go to Subtitles -> Subtitle Translation, and check `Always use` and `Lingva(Google) translate`

![Set to always use subtitle translation](https://github.com/user-attachments/assets/bbf832ac-e0fa-4e46-bb89-d468c327a834)

Enjoy it.

**Comment by gnh1201** [comment]
I saw what appears to be your Discord message. Please use HTTPS instead of HTTP. `https://translate.catswords.net`
